import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notes | Take App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/svg+xml" href="./notefy-logo.svg" />
      <body className={`${inter.className} bg-white text-textColor-200 `}>
        <Toaster />
        <AuthContextProvider>
         {children} 
        </AuthContextProvider>
      </body>
    </html>
  );
}
